### ISSUE TITLE
Output error on Elixir registry module example

### ISSUE THREAD

**Issue by GusGA** [hashrocket/tilex#269]
Hi, on this [example](https://til.hashrocket.com/posts/40fa5da0fe-the-registry-is-back) at the end of the code show this output:

```elixir
[{_, found_worker_pid}] = Registry.lookup(Registry.WorkerPids, :my_worker)
``` 
but according to the [docs](https://hexdocs.pm/elixir/Registry.html#lookup/2) the output of `Registry.lookup/2` is `[{pid(), value()}]` and not `[{value(), pid()}]`

👍

**Comment by tmock12** [comment]
I think the naming is making it confusing, but he's actually storing his `worker_pid` as the `value`:
```elixir
Registry.register(Registry.WorkerPids, :my_worker, worker_pid)
```
So then during the lookup his`found_worker_pid` is the `value`:
```elixir
[{_pid, found_worker_pid}] = Registry.lookup(Registry.WorkerPids, :my_worker)
```
That being said I do think there is a typo on the first line:
`{:ok, pid} = MyWorker.start_link()` should be `{:ok, my_worker_pid} = MyWorker.start_link()` as otherwise `my_worker_pid` isn't defined.

**Comment by jwworth** [comment]
The described post has been updated. Thanks @tmock12 and @GusGA! 👍 

Closing.
