### ISSUE TITLE
Move Post Category To Top of RSS Feed Articles

### ISSUE THREAD

**Issue by hashrocketeer** [hashrocket/tilex#283]
Requested by Twitter user [@earthrid](https://twitter.com/earthrid):

> As a daily reader of TIL via RSS, I feel compelled to suggest again that you move the category (in this case, "React") from the bottom of posts to the top. It would help readers know the context instantly - a point you seem to bear in mind with tweets but not on the site. KUTGW!

**Comment by earthrid** [comment]
Hi! I'm responding here to clarify my initial observation, in response to your tweet (https://twitter.com/hashrockettil/status/1009623042002182144)

Sorry if the wording was unclear. The point was simply that some posts lacked a clear indication of context right at the top. RSS is not an issue in itself, any more than any uncommented external link to a post would be (the tweets provide additional context, which is all well and good). Here's the essential part of my tweet:

"suggest again that you move the category (in this case, "React") from the bottom of posts to the top"

Here is my thinking in detail. (By the way, I am not in any way criticising the example post that follows or any other post but merely making a point about the way information _about_ the posts are sometimes presented ;) ).

For example this tweet linking to a post marks the subject domain as "#react" and also has a big graphic emblazoned with "#REACT". So by the time the link is clicked, the reader knows very well that the post is about React. A win for tweets.

Example post: https://til.hashrocket.com/posts/ytrzhrpfxk-proptypes-array-of-shape
Related tweet: https://twitter.com/hashrockettil/status/1004103597188055042

Now, approaching the same post via RSS rather than Twitter, the reader sees only what is on the Web page, and the post starts "PropTypes Array of Shape". OK, er... that's about um...? Well even if you know React, the penny might not drop immediately... Right at the bottom of the post there is a line which does include the tag "React"... It's the first and only time the word is used...

... So I wondered whether that line would be better placed at the top.

Now having said all that, an increasing number of posts do seem to include thematic context as part of their titles. For example, "Vim: Peek horizontally without moving the cursor" (https://til.hashrocket.com/posts/c8u6ymddbv-vim-peek-horizontally-without-moving-the-cursor)  clearly marks the post as being about Vim. There's no need to pause for thought there.

If you agree with me that it would be a good idea to have a consistent marker of thematic context in every post, all I am suggesting is: move the line at the bottom (the one with "#Vim", in this instance) to the top of posts. Alternatively, having a clear indicator of the subject in the headline is fine, and might be the way that you have decided to go in the meantime anyway!

Either way, I leave it all up to you, but hope that my point is at least now crystal clear! Many thanks for your time and posts.

**Comment by hashrocketeer** [comment]
Titles now include their channel name in production. May take a bit for your RSS feeder to update.

![image](https://user-images.githubusercontent.com/317960/43343946-b4b6bad8-91ad-11e8-9d8b-7900375e6c7c.png)

**Comment by earthrid** [comment]
I note that this concentrates on the RSS aspect rather than the Web page itself, but I agree that this may well be helpful. Thank you for your time and all the best.
