### ISSUE TITLE
Urls with multiple path segments where the first segment isn't a route or channel name 500

### ISSUE THREAD

**Issue by briandunn** [hashrocket/tilex#302]
# Steps to reproduce
Visit a url with a multi-segment path where the first part is not a channel or route, like
https://til.hashrocket.com/author/yourmom
### Expected behavior
I should see a 404 page
### Actual behavior
500
https://appsignal.com/5bb25369-c1b5-4dbb-afb3-7a42a12c81f4/sites/596cf062747820316ab83e56/incidents/3

**Comment by tmock12** [comment]
This was caused by commit https://github.com/hashrocket/tilex/commit/1a222b9a443190ea7a2c8bb87622a4a663b21c39

I think there are a couple of issues.

I'm not sure I agree with adding our layout with logic in it to the 404 or 500 page. To get it working you could change the following in `config.exs` 

```elixir
# confix.exs
render_errors: [layout: :app, view: TilexWeb.ErrorView, accepts: ~w(html json)],
```
to
```elixir
render_errors: [layout: {TilexWeb.LayoutView, :app}, view: TilexWeb.ErrorView, accepts: ~w(html json)],
```
but that's going to further showcase the problem with using our logic bound application layout because its going to blow up on the `get_flash/2` in the app layout and render a 500. 

comment out the following, and your mom, the author, is now a 404. 

```html
    <div id="flash">
      <%= if message = get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert">
          <%= message %>
        </p>
      <% end %>
    </div>
```

For a little background on why you can't find much information about using layouts in the error pages, you can look to this issue (https://github.com/phoenixframework/phoenix/issues/694). I tend to agree with Jose in that the error pages should be devoid of as much logic as possible.

**Comment by jwworth** [comment]
Really insightful analysis @tmock12 -- thank you. I think I agree Jose's point.  Perhaps we could find a middle ground, where the page looks like it's part of the app with all the CSS and dependencies, but it is self-contained? I'd be willing to work on that.

**Comment by jwworth** [comment]
This has been fixed.
