### ISSUE TITLE
Feature Request: Stream to Slack Channel

### ISSUE THREAD

**Issue by BenMorganIO** [hashrocket/tilex#328]
This project is fantastic! I know you can follow the project on Twitter, but I've been staying away from it to decrease my social media usage.

Is it possible to build an integration to Slack and track tags relevant to what a tech company specializes in?

**Comment by jwworth** [comment]
Thanks for the feedback!

For our company instance of TIL (AKA https://til.hashrocket.com/), we use https://github.com/hashrocket/tilex/blob/e0a5dbaf186427571062ed9411a56997204501cf/lib/tilex/notifications/notifiers/slack.ex to notify Slack whenever a post is created. It's been working great for years.

![image](https://user-images.githubusercontent.com/2782858/52012284-d0068900-249f-11e9-9d5c-2b27d86686b2.png)

If you're interested in following posts from the Hashrocket version of TIL, have you thought about a Twitter for Slack? You could set it up to follow the [@hashrockettil](https://twitter.com/hashrockettil) account. You would never have to visit Twitter, because our automated Tweets just post links to the site, which you could visit directly from Slack.

https://get.slack.help/hc/en-us/articles/205346227-Twitter-for-Slack

**Comment by dillonhafer** [comment]
I think we also have an RSS feed for TIL at: https://til.hashrocket.com/rss
