### ISSUE TITLE
Markdown Autolinking Failing

### ISSUE THREAD

**Issue by jwworth** [hashrocket/tilex#430]
Reported by @suzanne606 

### Steps to reproduce

Visit a post with a URL in the post body, that has not been turned into a link via an anchor tag or markdown link syntax.

### Expected behavior

Text should turn into a hyperlink with `href` the same as the text.

### Actual behavior

Text is displayed plainly (see screenshot).

### System configuration

Firefox

![image](https://user-images.githubusercontent.com/2782858/58338224-f6fd1800-7e0c-11e9-83cd-774debdafc9f.png)

**Comment by tmock12** [comment]
I looked into this a bit. This feature has been added to Earmark [1.3.3](https://github.com/pragdave/earmark/blob/master/CHANGELOG.md#133) but that version hasn't been released yet or tagged in Git. After that's released it appears to be as simple as adding an option of `pure_links: true` to our [EarmarkOptions](https://github.com/hashrocket/tilex/blob/master/lib/tilex/markdown.ex#L6)

My humble proposal would be to just wait a few weeks and see if this gets released rather than hacking something together and having to maintain it. As it's really just a nicety and we already have ways around it via markdown link syntax (`[text](url)`)

**Comment by tmock12** [comment]
Interesting that we had it before. I'll take a look back at Earmark history and see what it had in the past, maybe we can still use it. It looks like we did have a relative link expander with some functionality but it was disabled -> https://github.com/hashrocket/tilex/commit/de498353e00c23296f25edaa08563f63815028a5#diff-18124fa36681cb53241c78b3020a02ba

**Comment by vnegrisolo** [comment]
@jwworth as far as I understood the feature removed by Chris this was not related to auto link, but to make a relative link into a full url one. So I reenabled that feature for now on this PR #467, I tested with the example he got trouble with and it's passing. I also added a bunch of markdown tests as a way to guarantee we are outputting them right as we are doing a bit of manipulation on the markdown to html func.

Regarding this issue I agree with Taylor regarding waiting the new version of earmark.
