### ISSUE TITLE
Docker-based deployment

### ISSUE THREAD

**Issue by Quintasan** [hashrocket/tilex#532]
Hi,

I'm working on dockerizing tilex, would you guys be interested in a pull request with changes that are necessary for doing that?

**Comment by jwworth** [comment]
Thanks for submitting this idea!

The reason we don't have a Dockerfile or equivalent is because we deploy to Heroku (without using a container). Without regularly deploying a Docker container to production, we would have no way to ensure that the configuration works, or continues to work in the future. It’s a weird side effect of having an open source web application. Thanks again, and best of luck with the deployment!

**Comment by Quintasan** [comment]
@jwworth I belive that you can keep your current configuration without having to rely on Docker for your deployment to Heroku. From what I recall I only had to add a few environmental variables so that you can still deploy it without any containers if you feel like it.

**Comment by jwworth** [comment]
@Quintasan I'm not sure what changes you have in mind; feel free to open a PR. I can't guarantee we will merge it, but it will be in the history of the repo either way, and surely be useful to someone.
