### ISSUE TITLE
Reader Mode and Non-Reader Mode Don't Match

### ISSUE THREAD

**Issue by hashrocketeer** [hashrocket/tilex#620]
### Steps to reproduce

1. Visit the site
2. View the latest and greatest posts 👀
3. Turn on reader mode (Safari was tested)

### Expected behavior

I see the same list of posts in Reader Mode

### Actual behavior

I see a different list of posts in Reader Mode

### System configuration

iOS/Safari, OSX/Safari

Reader mode view:

![image](https://user-images.githubusercontent.com/317960/73468510-836fbb00-434a-11ea-930e-42dc7cd839d3.png)

Non-reader mode view:

![image](https://user-images.githubusercontent.com/317960/73468549-92566d80-434a-11ea-90b7-720a9db33eb0.png)

- Jake

**Comment by jwworth** [comment]
It's hard to pinpoint the cause of this; some posts render okay in Safari reader mode, others do not. These tools rely on semantically valid HTML to make sense of our content. We have some shortcomings there, so I'm going to open some PRs to improve our markup.

**Comment by jwworth** [comment]
Ok, I've worked on this for a while. The above PR's help, but I haven't tested every post page. Until they all look great, I'd like to keep the issue open.

Reader Mode is a bit of a black box; I could not find any official documentation. This post helped:

https://www.client9.com/designing-html-for-safari-reader-mode/

I no longer think that the post index page is the priority. Reader Mode seems to be really designed for individual articles. I don't believe our design, or the design of any HTML index page, is going to work 100% of the time in Reader Mode. Safari shouldn't be suggesting Reader Mode unless it is a good match for the HTML presented, and in the base of my bug report, I probably forced it to turn on out of curiosity. Show pages are going to work better, and thus be recommended by Safari, so that should be the priority.
